### PR TITLE
Mention a way to do React/Meteor integration

### PR DESCRIPTION
**Pull request by stubailo**
If you don't like this method, you can make a list of different options, but I think it would be useful to give people some pointers.

### CODE REVIEW

**Comment by ccorcos** [comment]
I'm just going to depreciate this package in favor of your packages which I'm already using haha.

That said, I'm curious what you think about this package I've been working on (hasn't been published)

https://github.com/ccorcos/meteor-react-ui

**Comment by stubailo** [comment]
Funny, I just added it to this page: http://react-in-meteor.readthedocs.org/en/latest/community/

I guess I'll remove it in favor of the other one which is essentially identical.

**Comment by ccorcos** [comment]
haha exactly.

**Comment by stubailo** [comment]
I like the idea, but isn't there an easier way to do this? Can't you just walk the React tree and get all of the state somehow without having to explicitly use instance.state everywhere?

**Comment by ccorcos** [comment]
Yeah, that would be ideal live-reloads. 

I'm not the biggest fan of having to use a mutable object... but its working pretty well thus far. I don't think mutable data is such a sin so long as you're simply saving and restoring in mount and unmount.

Also, its possible to put non-serializable data in your state. Plus, there may be some UI state like the scroll position to save. So its not just the component state itself that I want to save.

**Comment by ccorcos** [comment]
Its pretty cool ending up with a JSON object that represents the state of the entire UI:

``` js
{
    "state": {
        "title": "whales[3]",
        "currentTab": "whales"
    },
    "tabVCInstance": {
        "state": {
            "tabInstances": {
                "foxes": {
                    "state": {
                        "animation": "navvc-push",
                        "stack": [{
                            "sceneRoute": {
                                "path": "/",
                                "name": "/"
                            },
                            "instance": {
                                "state": {
                                    "limit": 5,
                                    "imgs": ["http://i.imgur.com/Hs1IbE7.jpg", "http://i.imgur.com/H6qktcz.jpg", "http://i.imgur.com/VHkN3EF.jpg", "http://i.imgur.com/zUn3x6S.jpg", "http://i.imgur.com/2eeKVAm.jpg"]
                                },
                                "scrollTop": 788
                            }
                        }, {
                            "sceneRoute": {
                                "name": "/foxes/:id",
                                "path": "/foxes/4",
                                "params": {
                                    "id": 4
                                }
                            },
                            "instance": {
                                "state": null,
                                "scrollTop": 0
                            }
                        }]
                    }
                },
                "whales": {
                    "state": {
                        "animation": "navvc-push",
                        "stack": [{
                            "sceneRoute": {
                                "path": "/whales",
                                "name": "/whales"
                            },
                            "instance": {
                                "state": {
                                    "limit": 4,
                                    "imgs": ["http://i.imgur.com/VLJOQr5.jpg", "http://i.imgur.com/1JzaSkb.jpg", "http://i.imgur.com/qoSFEkZ.jpg", "http://i.imgur.com/QLUGpps.jpg"]
                                },
                                "scrollTop": 687
                            }
                        }, {
                            "sceneRoute": {
                                "name": "/whales/:id",
                                "path": "/whales/3",
                                "params": {
                                    "id": 3
                                }
                            },
                            "instance": {
                                "state": null,
                                "scrollTop": 0
                            }
                        }]
                    }
                }
            }
        }
    }
}
```

**Pull request closed without merging**
